name: workout-tracker
services:
  # frontend:
  #   build: ./frontend
  #   networks:
  #     - client-side
  #   ports: 5000:5000
  #   environment:
  #     - name=value
  #   container_name: frontend


  # backend:
  #   container_name: restapi
  #   build: ./restapi
  #   ports:
  #     - 8080:8080


  postgres_db:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_USER: ${DBUSER}
      - POSTGRES_PASSWORD: ${DBPASS}
      - POSTGRES_DB: fitness_db
    container_name: fitness_db
    ports:
      - "5232:5232"
    volumes:
      - database:/var/lib/postgresql/data



volumes:
  database: