[package]
name = "restapi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum ="0.8"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres"] }